### ISSUE TITLE
libjpeg error centos 6.7

### ISSUE THREAD

**Issue by achekroud** [torch/image#152] opened 2016-03-13 14:58 UTC
Hi

I'm having some issues with the image package, specifically surrounding libjpeg. Libjpeg is installed already: 

```
[achekroud@cushing neural-style]$ ls /usr/lib64/libjp*
/usr/lib64/libjpeg.so  /usr/lib64/libjpeg.so.62  /usr/lib64/libjpeg.so.62.0.0
```

But I'm getting the following error when i run some code that tries to load libjpeg:

```
/home/achekroud/torch/install/share/lua/5.1/trepl/init.lua:384: ...chekroud/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libjpeg' from file '/home/achekroud/torch/install/lib/lua/5.1/libjpeg.so':
	/home/achekroud/torch/install/lib/lua/5.1/libjpeg.so: undefined symbol: jpeg_mem_src	
warning: <libjpeg> could not be loaded (is it installed?)	
/home/achekroud/torch/install/bin/luajit: /home/achekroud/torch/install/share/lua/5.1/dok/inline.lua:738: <image.loadJPG> libjpeg package not found, please install libjpeg
```

a more minimally reproducible error 

```
th
require 'image'
image.lena()
```

returns:

```
th> image.lena()
/home/achekroud/torch/install/share/lua/5.1/trepl/init.lua:384: ...chekroud/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libjpeg' from file '/home/achekroud/torch/install/lib/lua/5.1/libjpeg.so':
	/home/achekroud/torch/install/lib/lua/5.1/libjpeg.so: undefined symbol: jpeg_mem_src	
warning: <libjpeg> could not be loaded (is it installed?)	
(1,.,.) = 
 Columns 1 to 9
  0.7569  0.7765  0.7647.....
```

Any ideas how to solve this, or has anyone else had this problem before? I wonder if I just need to edit something in torch to tell it where libjpeg.so (and maybe libjpeg.h) are?

Thanks in advance
Adam

**Comment by soumith** [comment] 2016-03-13 15:12
you could try LD_PRELOAD=[path to your libjpeg.so]

**Comment by achekroud** [comment] 2016-03-13 16:09
Thanks for your suggestion, @soumith. I just tried, but unfortunately didn't work. Same errors remain, e.g:

```
/home/achekroud/torch/install/share/lua/5.1/dok/inline.lua:738: <image.loadJPG> libjpeg package not found, please install libjpeg
```

and 
```
 ...chekroud/torch/install/share/lua/5.1/luarocks/loader.lua:117: error loading module 'libjpeg' from file '/home/achekroud/torch/install/lib/lua/5.1/libjpeg.so':
```

weird that it seems to still be looking in `/install/lib/lua/5.1` even though I said 
```
export LD_PRELOAD = "/usr/lib64/libjpeg.so"
```
that was what you meant, right?

**Comment by deltheil** [comment] 2016-03-13 16:49
Looks like a duplicate of #41 i.e. you have `libjpeg-turbo-devel` properly installed and detected by torch/image. The problem is it only supports `JPEG_LIB_VERSION 62` (see `/usr/include/jconfig.h`) and `jpeg_mem_src`, etc require `JPEG_LIB_VERSION >= 80` (see `/usr/include/jpeglib.h`).

You should uninstall it and build libjpeg v8d from sources:

```bash
yum remove libjpeg-turbo-devel

cd /tmp && wget http://www.ijg.org/files/jpegsrc.v8d.tar.gz && \
tar xvf jpegsrc.v8d.tar.gz && \
cd jpeg-8d && \
./configure --prefix=/usr --libdir=/usr/lib64 && \
make && make install && \
ldconfig
```

**Comment by achekroud** [comment] 2016-03-14 13:39
@deltheil -- thanks!! I did this, and then combined it with @soumith's suggestion of LD_PRELOADing the exact libjpeg to use (libjpeg.so.8). Thanks a lot guys, I appreciate it.

**Closed** 2016-03-14 14:49 UTC
